name: core
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  connectivity_plus: ^5.0.2
  connectivity_plus_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: connectivity_plus_aurora-0.5.0
      path: packages/connectivity_plus/connectivity_plus_aurora
  core_tdlib_api:
    path: ../core_tdlib_api
  flutter:
    sdk: flutter
  rxdart: 0.27.3
  td_api:
    path: ../td/td_api

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules