name: td_client
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  rxdart: 0.27.3
  tdlib:
    git:
      url: https://github.com/TimoshN/tdlib-dart
      ref: master

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules