name: lottie_utils
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  archive: 3.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: path_provider_aurora-0.5.0
      path: packages/path_provider/path_provider_aurora

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../tg_lint_rules